platform :ios, '7.0'

pod 'AFNetworking', '~> 3.0'
#pod 'Hawk', '~> 0.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.7.2'
pod 'SSKeychain', '~> 1.2.3'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.9'
#pod 'Reachability', '~> 3.2'
#pod 'FMDB', '~> 2.5'

pod 'iOS-Slide-Menu', '~> 1.5'
#pod 'YALSideMenu', '~> 1.2.0'
#pod 'UPStackMenu', '~> 1.0.0'
#pod 'RESideMenu', '~> 4.0.7'
#pod 'REMenu', '~> 1.10'
#pod 'QBPopupMenu', '~> 2.0'
#pod 'PopMenu', '~> 2.4'
#pod 'PagingMenuController', '~> 0.7.8'
#pod 'PageMenu', '~> 1.2.8'
#pod 'DRSwipeMenu', '~> 2.0.1'
#pod 'ABMenuTableViewCell', '~> 2.0.0'

# 一些使用的View
#pod 'pop', '~> 1.0'
#pod 'STPopup', '~> 1.6.0'
#pod 'RWBlurPopover', '~> 3.1.0'
#pod 'Popover', '~> 0.8.0'
#pod 'NMPopUpViewSwift', '~> 3.0.1'

#pod 'TextFieldEffects', '~> 1.1.0'
#pod 'UITextField+Shake', '~> 1.1'
#pod 'FormTextField', '~> 0.7.2'
#pod 'RPSegmentedTextField', '~> 1.0.0'
#pod 'MRTextField', '~> 0.1.3'
#pod "MPNumericTextField", '~> 1.1.0'
#pod 'LRTextField', '~> 1.1.3'
#pod 'UIFloatLabelTextView', '~> 1.0.8'
#pod 'UIFloatLabelTextField', '~> 1.2.3'
#pod 'JVFloatLabeledTextField', '~> 1.1.0'
#pod 'CHDropDownTextField', '~> 1.0.0'
#pod 'CCValidatedTextField', '~> 1.1.1'
#pod 'RWDropdownMenu', '~> 1.0.3'
#pod 'DOPDropDownMenu-Enhanced', '~> 1.0.0'
#pod 'YawImageViewer', '~> 0.1.10'
#pod 'DropDownTableView', '~> 0.2'

#pod 'ZCAnimatedLabel', '~> 0.0.4'
#pod 'YXYNumberAnimationLabel', '~> 1.0.4'

#pod 'TYAttributedLabel', '~> 2.5.6'
#pod 'TTCounterLabel', '~> 1.2.0'
#pod 'MarqueeLabel', '~> 2.4.2'
#pod 'MZTimerLabel', '~> 0.5.4'
#pod 'MLLabel', '~> 1.9.0'
#pod 'KAProgressLabel', '~> 3.2'
#pod 'AutoScrollLabel', '~> 0.4.3'
#pod 'LCAnimatedPageControl', '~> 1.1.0'
#pod 'KYAnimatedPageControl', '~> 1.0.5'

#pod 'ZFRippleButton', '~> 0.5.1'
#pod 'WYMaterialButton', '~> 0.2.3'
#pod 'VBFPopFlatButton', '~> 0.0.6'
#pod 'UITintedButton', '~> 1.01'
#pod 'TKAnimatedCheckButton', '~> 0.3'
#pod 'SVGPlayButton', '~> 0.3.0'
#pod 'SDevCircleButton', '~> 0.0.1'
#pod 'PPiFlatSegmentedControl', '~> 1.4.0'
#pod 'SDevFlatColors', '~> 1.0.0'
#pod 'SDRecordButton', '~> 1.0.2'
#pod 'DLRadioButton', '~> 1.4.4'
#pod 'RMSaveButton', '~> 0.1.0'
#pod 'ProcessButton', '~> 0.2.0'
#pod 'HTPressableButton', '~> 1.3.2'
#pod 'DKCircleButton', '~> 1.1'
#pod 'DCPathButton', '~> 2.1.3'
#pod 'CatZanButton', '~> 1.2.2'
#pod 'BFPaperButton', '~> 2.0.18'

#pod 'PhotoSlider', '~> 0.13.1'
#pod 'ImageSlideshow', '~> 0.2.3'
#pod 'XNLoopBannerView', '~> 0.2'
#pod 'LCBannerView', '~> 1.0.0'
#pod 'JHBannerView', '~> 1.5.1'
#pod 'DYMRollingBanner', '~> 2.1.5'
#pod 'MessageBanner', '~> 1.0.4'
#pod 'GKLParallaxPictures', '~> 0.1.0'
#pod 'VKAssetsPickerController', '~> 1.0.2'
#pod 'UzysAssetsPickerController', '~> 0.9.9'
#pod 'TSAssetsPickerController', '~> 1.2'
#pod 'TNKImagePickerController', '~> 2.0.0'
#pod 'TLCityPicker', '~> 1.0.0'
#pod 'QBImagePickerController', '~> 3.4.0'
#pod 'FacebookImagePicker', '~> 2.0.7'
#pod 'FPPicker', '~> 5.1.3'
#pod 'CTAssetsPickerController', '~> 3.2.2'
#pod 'BUKImagePickerController', '~> 0.1.10'
#pod 'YSViewer', '~> 0.3'
#pod 'XHTwitterPaggingViewer', '~> 0.7'
#pod 'RDImageViewerController', '~> 0.3.9'
